### ISSUE TITLE
Implement auto-update from github:

### ISSUE THREAD

**Issue by bsavery** [bsavery/RenderManForBlender#402]
https://github.com/CGCookie/blender-addon-updater

**Comment by jdent02** [comment]
I can take a look at this......

**Comment by jdent02** [comment]
It's integrated and seems to work.  It isn't registering any release after 0.9.0 though.  Looking at the release page you changed the formatting after the 0.9.0 release and I guess this updater doesn't agree with it......

**Comment by jdent02** [comment]
![image](https://cloud.githubusercontent.com/assets/13521172/20822019/d23015e0-b80c-11e6-8282-b0e0eacce75c.png)

**Comment by bsavery** [comment]
Doesn't agree with it why?

**Comment by bsavery** [comment]
Cool though!

**Comment by jdent02** [comment]
The formatting of the release tag I think.  for 0.9.0 you had 'v0.9.0' and after than you didn't use the 'v' or '.' in the tag.  I think it cues off those.

**Comment by jdent02** [comment]
I could manually update to the latest master just fine.  I think this'll help people stay up to date, especially if they turn on automatic checking.

**Comment by enzyme69** [comment]
This is awesome I will try soon!

**Comment by jdent02** [comment]
So when I added this I changed the following setting to True:

# allow 'master' as an option to update to, skipping any releases.
# releases are still accessible from re-install menu
updater.include_master = True

On second thought I'm not sure this was a good idea since if I'm reading that right it won't automatically prompt users to update to release versions.  Maybe I should set that back to false?  The user can still manually update to master but the automatic check would only look for releases.  That's if I'm reading it right......

**Comment by jdent02** [comment]
Umm I might be reading the code wrong, but there's a parameter I flipped to True

updater.use_master

And I think this is going to cause the auto updater to prompt users to update very single time they start the addon.
